---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: false

ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.py"

exclude_paths:
- .gitignore
- .travis.yml
- .codecov.yml
- .codeclimate.yml
- README.md
- node_modules/**/*
- test/**/*
- codeclimate.yml
