language: node_js
node_js:
- '5'
- '4'
notifications:
  slack:
    secure: ACS2x3/JYhHyCFN3asvh70YyTiUOnZjxEVDz3t0h7v9KmM1zNjEMX0c5EpDYnQG/hELSBJjulUwaMlRigOOSkC1GM1gMvFiGZOGEX1Jr522UIzhbzpYRfvB58zY6Inna++wkCOtx1638t2Ngps1Zlor8jDnfxvHQAyNBG9IOqNv4Z9zxJsIDQOWFHsm6ZPr8A9bEHAntR5Ds69FPJBJqPXFQdxppS76aL/NBLoDD2dA3hm4w24j7ZLFmtaUkpX21ztcxuJq1JIJG/CNsvRnrfA1Wh0AbcJtlbjomjbNk6PUa+Kwi26bbTtpY5PsBCO6vJjH7i7Qv9b6SCRxlKTLncnJYLOo8zq0/aTnAHc5nHstC6o/twhEd+jHfk37HT0EGAdq545WwvNyR52JQYUnCvrdrVBapjTSVQXcXKImuzl49+csA5V3QjdbxGho3MY0wEcFpGN+HQ0I4H5YRkWK876L6qA9VsICVspKlpY/S1EozBgnAZpQK9z/4PZ/LjFgkV2iRNLXsnk0TqIwPU3xNakDSvYDDKPyi9BqWqPIO5wNxAw558yVF2j4pCkbygkN7jWjxK9Sy9031TF9p43RzCyfZRdgpCZTt6GkFTN669QpP9xdBquF0/LfZ0DrmVHBQJVAClSxoMTP5HqxSuSSwTSJy+pYJJvUNVKId9HusVjM=

after_success:
  - bash <(curl -s https://codecov.io/bash)
