codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: nearest
  range: "70...100"

  status:
    project:
      default:
        target: auto

    patch:
      default:
        target: auto

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
